services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - type: volume
        source: TANNDER_DATA
        target: /data/db
  server:
    build: .
    depends_on:
      - mongodb
    environment:
      DB_URI: mongodb://admin:admin@mongodb:27017/
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcloud.json
      PORT: 3000
    ports:
      - 3000:3000

volumes:
  TANNDER_DATA:
    name: TANNDER_DATA
