services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
  server:
    build: .
    depends_on:
      - mongodb
    environment:
      DB_URI: mongodb://admin:admin@mongodb:27017/
      PORT: 8080
    ports:
      - 80:8080

volumes:
  MONGO_DATA:
    name: MONGO_DATA
