name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-client:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./client
        run: npm i
      - name: Run ESLint
        working-directory: ./client
        run: npm run lint

  lint-server:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./server
        run: npm i
      - name: Run ESLint
        working-directory: ./server
        run: npm run lint
